### PR TITLE
update screeps dep. to safe version

### PR DESCRIPTION
**Pull request by CarsonBurke**

### CODE REVIEW

**Comment by CarsonBurke** [comment]
@Jomik 
previous versions of the server have major security issues that this update should resolve.
I have not tested this yet.

**Comment by CarsonBurke** [comment]
I have now tested it and had no issues.
also, any chance I could have some permissions over this repo to maintain it?

**Comment by Jomik** [comment]
The package.json actually does not currently control what is used when building this image. I intended to have it as dependency and then use something like dependabot to trigger updates automatically.
I will look at setting that up now so that it happens automatically.

**Comment by Jomik** [comment]
> I have now tested it and had no issues. also, any chance I could have some permissions over this repo to help maintain it?

Thanks! I am unsure what maintenance you are thinking of? Version updates should now be automated using dependabot. Development itself I would still like to be core part of, so if you have any suggestions or changes there, I would prefer it go through a PR so that I can scrutinize it first 😄

**Comment by Jomik** [comment]
Fixed #18

**Pull request closed without merging**
